language: go
go:
  - 1.3
  - 1.5
  - tip
script: go test ./... -v && go build
before_deploy:
        - mkdir -p ovirt-prometheus-bridge-$TRAVIS_TAG/bin && mv ovirt-prometheus-bridge  ovirt-prometheus-bridge-$TRAVIS_TAG/bin/
        - tar -cvzf ovirt-prometheus-bridge-$TRAVIS_TAG.tar.gz ovirt-prometheus-bridge-$TRAVIS_TAG/bin
after_deploy:
        - |-
          curl -H "Content-Type: application/json" --data "{\"source_type\": \"Tag\", \"source_name\": \"$TRAVIS_TAG\"}" -X POST https://registry.hub.docker.com/u/rmohr/ovirt-prometheus-bridge/trigger/$DOCKER_HUB_TOKEN/
        - sleep 180
        - |-
          curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "master"}' -X POST https://registry.hub.docker.com/u/rmohr/ovirt-prometheus-bridge/trigger/$DOCKER_HUB_TOKEN/
env:
  global:
    - secure: onw2jPsXYcu5grEep8wuVNf16jetXS+vDEuXaWYnfphB1Qu3JseNPOqLz1/YinI8nCAkOoMS+CpWRX5H0GkLlouizioNxRaPt8sw+B+XyiWsH5s1OnJUADAS9WRQB5BUfRpkFC2DAyaR4EvGlfZOu6CHh9nKuHLRW0jTT/2hXKbjgsnkqa1M86+z78308Rzdtrtses/4mvJAY2Xc6N+TiJtJtZKJ+zn4+FCyuzBko0Z2ocIXr4i500cQtLqhzha1c3nKooB25wDd+B39yoH5b8fot9zg+0jT/isUfhEkPUC5yNcQCsMg87IZ2mSa7td8Gh3XB6AzN/FLxUXZrN1+rpi5ClRjO1AjoN+0qh/OsesWY2tbgiR81OB+Y2QPVoQuCB15Z1hT5IB2emJTUJ4xVUI16NlU+Y9zQBGK+8PqdWUT/IcM0SdCW0lmCiUx6kbl9rIGf4kRLKFQHg+a3HVmQEvaFH774yMRin45qLarGv+eY502fYPjvl15M4Ey/V6o10avWQ9pndwfPRGOhCofYgKBrHFPi0bTpAyPNFFNg1gMCHru7IOI23fG9e/aqyocUEFmAcdDl1XBN+Aits9MzGEbup9vssZfUM8fXFimk/xit+xlTF5cYe04iZDuJv+EMMhDQks6urnA75omXFhct2AwC7XIoqOFG0MWsQATsEI=
deploy:
  provider: releases
  api_key:
    secure: AKTPi1OEbSKMyeakkRSckUmJZQN5DWSxPL99v3uS4oUzm8xjlBBHslSOnFQcL9NgCRyXTOgocreoRBqcLQkgC0JkXAL/IHMruE7wqatYjO+Pe8QfvgwLahma9VzDPm3qoVclP7Karx7+9uUGDE9FSsU/Nuk2s5nj5dkvM7eT4GTk7qFNUVuOC+df1jsmrH8gzu/QabkvQ5gWPW0emPSBvWfkqfDzXJy+1UzjIQ9CtjqYKIeR86C/tlOWICje3CSx+8TI9YI3De+bMmH5ep3x7qNIOCLSyyx/kvdxPxhBxY8QTbh4aCpU+10o3CYp9Rm/UhAHc5cQbAz8A8nYdLoOG/YJiSxPQdwKukyPfHnT1RWe5VHD7qHYIOGzXUrcDeIdp1pUWS6fPc63TDZTP4G+f/vWMYB16iFTz47Gzgo8A6AsKLZwakfDXpRyZBgPV2wx/zTrq70rw1e4aftBH+SpfDWnW9GQfphGb7liyxH8zMDT/FDOcQCNeEhpLos+j53gMwA4PAdNZ3pTTgLboJ3B7oHccRYz4FoOTp1nLYL7NDAMJsic0L6suWkgBz1bgiDstdcVxazQZ+jcA69ZbCTGg8K7fotZQK/FsB6940vZ9jaL8Xo/8zUWfl/ygE0VuBwNji+zqkfuxr874c1OrjMvvny7lXbbPlgRN4LCjLmUMe0=
  file: ovirt-prometheus-bridge-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    repo: rmohr/ovirt-prometheus-bridge
    tags: true
    go: '1.5'

